added "meta" as in https://github.com/schul-cloud/gamification/issues/53
frederike-ramin/gamification pull request #71
Opened 2018-11-07 21:27 UTC by catamaican

2018-11-15 08:03 UTC, janrenz requested changes
Thanks for your contribution, can you add tests and docs please?

2018-11-15 08:03 UTC, janrenz commented on src/index.js
> +// const amqpConnector = new AmqpConnector(app.get('rabbitmq'), app);
if you want to disable this we should make it configurable

2018-11-15 08:06 UTC, janrenz commented
Also the title should reflect that leaderboards are intorduced hre as well :)

2018-11-19 12:49 UTC, cmfcmf requested changes
Hey @catamaican, thank you for contributing!
I've left a few comments and questions regarding your code.
Also, for this to be merged, make sure to include tests and documentation as requested by @janrenz.

2018-11-19 12:49 UTC, cmfcmf commented on src/hooks/leaderboard-actions.js
> +    ///>>> tradus in MongoShell= db.xps.aggregate([.....]);
Could you translate this to English?

2018-11-19 12:49 UTC, cmfcmf commented on src/rule-parser.js
> +    this.meta = rule['meta'] === undefined ? [] : rule['meta'];
I think this should default to `{}` instead of `[]`.

2018-11-19 12:49 UTC, cmfcmf commented on src/services/user/user.class.js
> +      value: value
What does `value` stand for?

2018-11-19 12:49 UTC, cmfcmf commented on src/models/achievement.model.js
> +    meta: {type: Map, required: false, default: {}}
Saving `meta` to the database should not be strictly necessary. Instead, metadata could be fetched from the config everytime the achievement model is queried.

2018-11-19 12:49 UTC, cmfcmf commented on package-lock.json
> +          "optional": true,
How did all of them become optional? Can you tell us your NPM version?

2018-11-19 12:49 UTC, cmfcmf commented on src/models/leaderboard.model.js
> +};
You shouldn't need this model class - similarly how the user service also doesn't use a user model.

2018-11-27 21:20 UTC, corinnaj requested changes
Thanks for contributing!
If you have any questions on the changes requested, feel free to leave them as comments so we can help you further.

2018-11-27 21:20 UTC, corinnaj commented on src/services/leaderboard/leaderboard.service.js
> +// Initializes the `Leaderboard` service on path `/leaderboard`
Ideally, the changes for #65 should be moved to a second PR in a new branch. This makes the reviewing process easier and also allows you to test each feature independently.

2018-11-27 21:20 UTC, corinnaj commented on src/services/leaderboard/leaderboard.class.js
> +class Service {
Is this class being used anywhere?

2026-02-18 06:46 UTC, closed without merging